In [1]:
import pandas as pd
import numpy as np

In [23]:
data_ngfs = pd.read_excel(
    "data/ngfs_data/ngfs_macro_trimestriel.xlsx"
)

data_ngfs['variable'].unique()

array(['Central bank Intervention rate (policy interest rate)',
       'Consumption (private)', 'Domestic demand',
       'Effective exchange rate', 'Exchange rate',
       'Exports (goods and services)', 'GDP Growth Rate',
       'Gov. consumption', 'Imports (goods and services)',
       'Inflation rate', 'Investment (gov.)',
       'Investment (private sector)', 'Long term interest rate',
       'Long term real interest rate',
       'Trend output for capacity utilisation', 'Unemployment rate',
       'Carbon pricing', 'Coal price', 'Energy consumption (total)',
       'Equity prices', 'Gas price', 'Gross domestic income',
       'Gross operating surplus', 'House prices (residential)',
       'Oil price', 'Productivity (output per hour worked)',
       'Quarterly consumption of coal', 'Quarterly consumption of gas',
       'Quarterly consumption of non-carbon',
       'Quarterly consumption of oil', 'Real personal disposable income',
       'Revenue from CB or BCA tax',
       'Volume energy use as a share of GDP'], dtype=object)

In [19]:
data_nigem = pd.read_excel(
    "data/ngfs_data/NiGEM_data.xlsx"
)

data_nigem.head()

,Model,Scenario,Region,Variable,Unit,2022,2023,2024,2025,2026,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
0,NiGEM NGFS v1.24.2[GCAM 6.0 NGFS],Delayed transition,NiGEM NGFS v1.24.2|Africa,Carbon pricing ; $ per Tn CO2(combined(no bus)),Abs. difference,0.0,0.0,0.0,0.0,0.0,...,1276.70813,1442.656372,1608.604614,1774.552856,1940.501221,2139.177490,2357.489990,2575.802490,2794.114990,3012.427490
1,NiGEM NGFS v1.24.2[GCAM 6.0 NGFS],Delayed transition,NiGEM NGFS v1.24.2|Africa,Carbon pricing ; $ per Tn CO2(combined),Abs. difference,0.0,0.0,0.0,0.0,0.0,...,1276.70813,1442.656372,1608.604614,1774.552856,1940.501221,2139.177490,2357.489990,2575.802490,2794.114990,3012.427490
2,NiGEM NGFS v1.24.2[GCAM 6.0 NGFS],Delayed transition,NiGEM NGFS v1.24.2|Africa,Carbon pricing ; $ per Tn CO2(physical),Abs. difference,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,NiGEM NGFS v1.24.2[GCAM 6.0 NGFS],Delayed transition,NiGEM NGFS v1.24.2|Africa,Carbon pricing ; $ per Tn CO2(transition),Abs. difference,0.0,0.0,0.0,0.0,0.0,...,1276.70813,1442.656372,1608.604614,1774.552856,1940.501221,2139.177490,2357.489990,2575.802490,2794.114990,3012.427490
4,NiGEM NGFS v1.24.2[GCAM 6.0 NGFS],Delayed transition,NiGEM NGFS v1.24.2|Africa,Central bank Intervention rate (policy interes...,Abs. difference,0.0,0.0,0.0,0.0,0.0,...,0.40323,0.439659,0.489981,0.553510,0.624617,0.575285,0.543899,0.545294,0.567778,0.611295

In [26]:
[
'Central bank Intervention rate (policy interest rate)',
'Effective exchange rate',
'Equity prices',
'GDP Growth Rate',
'House prices (residential)',
'Inflation rate',
'Long term interest rate',
'Oil price',
'Unemployment rate'
]

['Central bank Intervention rate (policy interest rate)',
 'Effective exchange rate',
 'Equity prices',
 'GDP Growth Rate',
 'House prices (residential)',
 'Inflation rate',
 'Long term interest rate',
 'Oil price',
 'Unemployment rate']

In [27]:
NGFS_TO_MODEL = {
    "Central bank Intervention rate (policy interest rate)":
        "US_Central_bank_Intervention_rate_policy_interest_rate",

    "Effective exchange rate":
        "US_Effective_exchange_rate",

    "Equity prices":
        "US_Equity_prices",

    "GDP Growth Rate":
        "US_GDP_Growth_Rate",

    "House prices (residential)":
        "US_House_prices_residential",

    "Inflation rate":
        "US_Inflation_rate",

    "Long term interest rate":
        "US_Long_term_interest_rate",

    "Oil price":
        "US_Oil_price",

    "Unemployment rate":
        "US_Unemployment_rate",
}

In [28]:
data_ngfs["zone"] = data_ngfs["zone"].ffill()

In [29]:
data_ngfs.head()

,zone,variable,2022-Q1,2022-Q2,2022-Q3,2022-Q4,2023-Q1,2023-Q2,2023-Q3,2023-Q4,...,2047-Q4,2048-Q1,2048-Q2,2048-Q3,2048-Q4,2049-Q1,2049-Q2,2049-Q3,2049-Q4,2050-Q1
0,EU,Central bank Intervention rate (policy interes...,0.666667,1.594365,2.522064,3.449763,4.377462,4.494107,4.610752,4.727397,...,3.737243,3.737243,3.737243,3.737243,3.737243,3.737243,3.737243,3.737243,3.737243,3.737243
1,EU,Consumption (private),5967.662231,5975.562408,5983.462585,5991.362762,5999.262939,6006.761536,6014.260132,6021.758728,...,7510.032715,7522.438110,7534.423065,7546.408020,7558.392975,7570.377930,7581.977295,7593.576660,7605.176025,7616.775391
2,EU,Domestic demand,10909.079590,10922.391785,10935.703979,10949.016174,10962.328369,10984.926636,11007.524902,11030.123169,...,14444.852661,14482.053223,14519.342346,14556.631470,14593.920593,14631.209717,14668.538147,14705.866577,14743.195007,14780.523438
3,EU,Effective exchange rate,104.197612,105.617902,107.038192,108.458482,109.878772,110.332601,110.786430,111.240258,...,121.020298,121.133349,121.246840,121.360331,121.473822,121.587313,121.701236,121.815159,121.929082,122.043005
4,EU,Exchange rate,104.197612,103.476717,102.755823,102.034928,101.314034,101.137369,100.960704,100.784040,...,99.624373,99.624373,99.624373,99.624373,99.624373,99.624373,99.624373,99.624373,99.624373,99.624373

In [30]:
def build_X_from_ngfs_trimestriel(df_ngfs, zone, var_mapping):

    # 1️⃣ Filtrer zone US
    df = df_ngfs[df_ngfs["zone"] == zone].copy()

    # 2️⃣ Garder uniquement variables utiles
    df = df[df["variable"].isin(var_mapping.keys())].copy()

    # 3️⃣ Colonnes trimestrielles
    quarter_cols = [c for c in df.columns if "-Q" in str(c)]

    # 4️⃣ Wide → long
    df_long = df.melt(
        id_vars=["zone", "variable"],
        value_vars=quarter_cols,
        var_name="date",
        value_name="value"
    )

    # 5️⃣ Convertir date
    df_long["date"] = pd.PeriodIndex(df_long["date"], freq="Q").to_timestamp()

    # 6️⃣ Renommer variables selon ton modèle
    df_long["var_model"] = df_long["variable"].map(var_mapping)

    # 7️⃣ Pivot final : dates × variables
    X = df_long.pivot_table(
        index="date",
        columns="var_model",
        values="value",
        aggfunc="mean"
    ).sort_index()

    return X

In [32]:
macro_cols = [
    'US_Central_bank_Intervention_rate_policy_interest_rate',
    'US_Effective_exchange_rate',
    'US_Equity_prices',
    'US_GDP_Growth_Rate',
    'US_House_prices_residential',
    'US_Inflation_rate',
    'US_Long_term_interest_rate',
    'US_Oil_price',
    'US_Unemployment_rate'
]

In [33]:
X_scenario = build_X_from_ngfs_trimestriel(
    df_ngfs=data_ngfs,
    zone="US",
    var_mapping=NGFS_TO_MODEL
)

# Mettre dans le bon ordre
X_scenario = X_scenario[macro_cols]

X_scenario.head()

var_model,US_Central_bank_Intervention_rate_policy_interest_rate,US_Effective_exchange_rate,US_Equity_prices,US_GDP_Growth_Rate,US_House_prices_residential,US_Inflation_rate,US_Long_term_interest_rate,US_Oil_price,US_Unemployment_rate
date,,,,,,,,,
2022-01-01,1.895833,110.233435,157.738774,0.328440,136.802637,8.007718,2.951667,98.996328,3.641666
2022-04-01,2.748228,110.349450,158.250548,0.328440,138.785644,7.177069,3.203569,95.141495,3.638935
2022-07-01,3.600623,110.465465,158.762322,0.328440,140.768650,6.346419,3.455472,91.286663,3.636204
2022-10-01,4.453018,110.581481,159.274096,0.328440,142.751657,5.515769,3.707374,87.431830,3.633473
2023-01-01,5.305413,110.697496,159.785870,2.463064,144.734664,4.685120,3.959277,83.576998,3.630742

In [34]:
X_scenario.to_csv("data/ngfs_data/ngfs_us.csv")